# Generated by Django 6.0.6 on 2026-06-10 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=25)),
                ('language', models.CharField(choices=[('en', 'English'), ('bn', 'বাংলা (Bengali)'), ('hi', 'हिन्दी (Hindi)'), ('ur', 'اردو (Urdu)'), ('ar', 'العربية (Arabic)'), ('fr', 'Français (French)'), ('es', 'Español (Spanish)'), ('pt', 'Português (Portuguese)'), ('sw', 'Kiswahili (Swahili)'), ('zh', '中文 (Chinese)')], default='en', max_length=10)),
                ('primary_crop', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Nitrogen', models.FloatField()),
                ('Phosphorus', models.FloatField()),
                ('Potassium', models.FloatField()),
                ('Temperature', models.FloatField()),
                ('Humidity', models.FloatField()),
                ('pH', models.FloatField()),
                ('Rainfall', models.FloatField()),
                ('predicted_crop', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
