# Generated by Django 6.0.6 on 2026-06-10 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_index', models.PositiveSmallIntegerField(help_text='0=primary, 1=secondary, 2=emergency')),
                ('db_key_id', models.IntegerField(blank=True, help_text='AIKeyConfig.id if DB-managed', null=True)),
                ('model_used', models.CharField(max_length=60)),
                ('success', models.BooleanField()),
                ('error_type', models.CharField(blank=True, max_length=200)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('agent_type', models.CharField(blank=True, max_length=80)),
                ('is_failover', models.BooleanField(default=False, help_text='True when a backup key/model was used')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'AI Call Log',
                'verbose_name_plural': 'AI Call Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AIKeyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="E.g. 'Primary Key', 'Backup Key 1'", max_length=100)),
                ('api_key', models.CharField(help_text='Gemini API key from Google AI Studio', max_length=500)),
                ('priority', models.PositiveSmallIntegerField(default=2, help_text='Lower number = higher priority. 1=Primary, 2=Secondary, 3=Emergency')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable without deleting')),
                ('notes', models.TextField(blank=True, help_text='Optional notes (e.g. quota limit, project)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Gemini API Key',
                'verbose_name_plural': 'Gemini API Keys',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DigitalTwin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_profile', models.JSONField(default=dict, help_text='Computed behavioral profile used by AI agents')),
                ('crops_grown', models.JSONField(default=list)),
                ('preferred_categories', models.JSONField(default=list)),
                ('budget_range', models.CharField(blank=True, default='medium', max_length=20)),
                ('brand_preferences', models.JSONField(default=list)),
                ('disease_history', models.JSONField(default=list)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_spent_bdt', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_frequency', models.CharField(blank=True, default='monthly', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_twin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Digital Twin',
                'verbose_name_plural': 'Customer Digital Twins',
            },
        ),
        migrations.CreateModel(
            name='MerchantTwin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_cache', models.JSONField(default=dict, help_text='Cached analytics used by MerchantAgent')),
                ('top_products', models.JSONField(default=list)),
                ('revenue_trend', models.JSONField(default=dict)),
                ('customer_segments', models.JSONField(default=dict)),
                ('seasonal_patterns', models.JSONField(default=dict)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_orders_served', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_twin', to='accounts.useraccount')),
            ],
            options={
                'verbose_name': 'Merchant Digital Twin',
                'verbose_name_plural': 'Merchant Digital Twins',
            },
        ),
    ]
