# Generated by Django 6.0.6 on 2026-06-10 17:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropDiseaseScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/crop_disease/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('crop_name', models.CharField(blank=True, max_length=200)),
                ('predicted_class', models.CharField(blank=True, max_length=200)),
                ('confidence', models.CharField(blank=True, max_length=20)),
                ('severity', models.CharField(blank=True, max_length=50)),
                ('is_healthy', models.BooleanField(blank=True, null=True)),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('causes', models.JSONField(blank=True, default=list)),
                ('treatment_steps', models.JSONField(blank=True, default=list)),
                ('prevention_tips', models.JSONField(blank=True, default=list)),
                ('additional_notes', models.TextField(blank=True)),
                ('marketplace_products', models.JSONField(blank=True, default=list)),
                ('product_narrative', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_disease_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crop Disease Scan',
                'verbose_name_plural': 'Crop Disease Scans',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'status', '-uploaded_at'], name='crop_diseas_user_id_bf3f71_idx'), models.Index(fields=['status', '-uploaded_at'], name='crop_diseas_status_c99c1e_idx')],
            },
        ),
    ]
